{% set name = "sagemaker-kernel-wrapper" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d97598e08422868d26baef74c9302e299dc8463f258ef03d622dd3f44e6b80d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - boto3

test:
  imports:
    - sagemaker_kernel_wrapper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker
  summary: SageMaker Kernel Wrapper Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - just4brown
