{% set name = "sagemaker-kernel-wrapper" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sagemaker-kernel-wrapper-{{ version }}.tar.gz
  sha256: 7255127506d0cb5c5b84f11fc9940716b8851822fbed606bf504abdc1e80536c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - boto3

test:
  imports:
    - sagemaker_kernel_wrapper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker
  summary: SageMaker Kernel Wrapper Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nileshvd
    - just4brown
    - nargokul
    - pintaoz-aws
    - benieric
    - mufaddal-rohawala
    - C24IO
    - Aditi2424
